window.SHIELDBEARER_RUNTIME_CONFIG = window.SHIELDBEARER_RUNTIME_CONFIG || {};

if (!window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN) {
  window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN = '';
}

if (!window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN) {
  window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN = '';
}

if (!window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_FEATURED_COLLECTION_HANDLE) {
  window.SHIELDBEARER_RUNTIME_CONFIG.NEXT_PUBLIC_SHOPIFY_FEATURED_COLLECTION_HANDLE = 'featured-homepage';
}
