window.SHOPIFY_CONFIG = window.SHOPIFY_CONFIG || {};

if (!window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN) {
  window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN = 'shop.shieldbearerusa.com';
}

if (!window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN) {
  window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN = 'REPLACE_WITH_PUBLIC_STOREFRONT_TOKEN';
}

if (!window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_FEATURED_COLLECTION_HANDLE) {
  window.SHOPIFY_CONFIG.NEXT_PUBLIC_SHOPIFY_FEATURED_COLLECTION_HANDLE = 'featured-homepage';
}
